version: '3'
services:
  app-service:
    # command: ['sh', 'docker-entrypoint.sh']
    image: node:latest:latest
    platform: linux/arm64/v8
    stdin_open: true
    volumes:
      - app-unison-sync:/home/docker/apps:nocopy

volumes:
  app-unison-sync:
      name: ${SYNC_NAME}-unison-sync