version: '3'
services:
  app-service:
    # command: ['sh', 'docker-entrypoint.sh']
    image: emirdeliz/cpp-opencv:latest
    stdin_open: true
    volumes:
      - app-unison-sync:/home/docker/apps:nocopy

volumes:
  app-unison-sync:
      name: ${SYNC_NAME}-unison-sync