version: '3'
services:
  app-service:
    image: ${DOCKER_IMAGE}
    platform: ${DOCKER_IMAGE_PLATFORM}
    stdin_open: true
    volumes:
      - app-unison-sync:/home/docker/apps:nocopy
      - ~/.ssh:/root/.ssh

volumes:
  app-unison-sync:
      name: ${SYNC_NAME}-unison-sync